"""
End-to-end integration test: adapter import/export roundtrip.

This test verifies that agents can be imported from each supported AI tool format
and converted to valid Agent JSON v2, then loaded by the runtime.

Uses Python adapters directly (no Node.js dependency).
"""

import json
import sys
import tempfile
from pathlib import Path

import pytest

# Add agent-compose to path
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "agent-compose"))

from agent_compose.adapters import (
    CursorAdapter,
    ClaudeAdapter,
    CodeBuddyAdapter,
    GitHubAdapter,
    VSCodeAdapter,
    JetBrainsAdapter,
    OpenAIGPTsAdapter,
    AdapterRegistry,
)
from agent_compose.agent_runtime import AgentRuntime


# Sample markdown content for each adapter format
SAMPLE_CURSOR_MD = """# Test Cursor Agent

This is a test agent imported from Cursor format.

## Usage

Run this agent to perform a simple task.
"""

SAMPLE_CLAUDE_MD = """# /test-claude-agent — Test Claude Agent

## Description

A test agent imported from Claude Code format.

## Steps

1. Analyze the request
2. Generate a response
"""

SAMPLE_CODEBUDDY_MD = """---
name: test-codebuddy-agent
version: 1.0.0
description: A test agent imported from CodeBuddy format
---

<!-- codebuddy:skill name="test-codebuddy-agent" -->

# Test CodeBuddy Agent

This agent demonstrates CodeBuddy skill import.
"""

SAMPLE_GITHUB_MD = """# Test GitHub Copilot Agent

> AI agent prompt – generated by agent-deploy v2.0

This is a test agent imported from GitHub Copilot format.

## Instructions

Perform a helpful coding task.
"""

SAMPLE_VSCODE_MD = """# Test VSCode Prompt Agent

This is a test agent imported from VS Code prompt format.

## Usage

Use this prompt to assist with coding.
"""

SAMPLE_JETBRAINS_MD = """# Test JetBrains AI Agent

This is a test agent imported from JetBrains AI Assistant format.

## Instructions

Assist the user with development tasks.
"""

SAMPLE_OPENAI_MD = """# Test OpenAI GPTs Agent

This is a test agent imported from OpenAI GPTs format.

## Instructions

Act as a helpful assistant.
"""

ADAPTER_SAMPLES = {
    "cursor": (".cursor/commands/test-cursor-agent.md", SAMPLE_CURSOR_MD),
    "claude_code": (".claude/commands/test-claude-agent.md", SAMPLE_CLAUDE_MD),
    "codebuddy": (".codebuddy/skills/test-codebuddy-agent/SKILL.md", SAMPLE_CODEBUDDY_MD),
    "github_copilot": (".github/agents/test-github-agent.md", SAMPLE_GITHUB_MD),
    "vscode_agent_mode": (".vscode/agents/test-vscode-agent.md", SAMPLE_VSCODE_MD),
    "jetbrains_ai_assistant": (".idea/ai-assistant/test-jetbrains-agent.md", SAMPLE_JETBRAINS_MD),
    "openai_gpts": ("gpts/test-openai-agent.json", None),  # JSON format, handled separately
}

ADAPTER_CLASSES = {
    "cursor": CursorAdapter,
    "claude_code": ClaudeAdapter,
    "codebuddy": CodeBuddyAdapter,
    "github_copilot": GitHubAdapter,
    "vscode_agent_mode": VSCodeAdapter,
    "jetbrains_ai_assistant": JetBrainsAdapter,
    "openai_gpts": OpenAIGPTsAdapter,
}


SAMPLE_OPENAI_JSON = json.dumps({
    "name": "Test OpenAI GPT",
    "description": "A test GPT for e2e validation",
    "instructions": "You are a test assistant.",
    "conversation_starters": ["Hello", "Help me"],
    "capabilities": ["web_browsing"]
}, indent=2)


@pytest.fixture(scope="module")
def adapter_temp_dir():
    """Create a temporary directory containing sample files for all adapters."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir)
        for tool, (rel_path, content) in ADAPTER_SAMPLES.items():
            file_path = base / rel_path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            if content is not None:
                file_path.write_text(content, encoding="utf-8")
            else:
                # OpenAI GPTs uses JSON
                file_path.write_text(SAMPLE_OPENAI_JSON, encoding="utf-8")
        yield base


class TestAdapterRoundtrip:
    """Adapter import/export roundtrip end-to-end tests."""

    @pytest.mark.parametrize("tool_name", list(ADAPTER_SAMPLES.keys()))
    def test_adapter_can_import(self, adapter_temp_dir, tool_name):
        """Each adapter can detect and import its sample file."""
        rel_path, _ = ADAPTER_SAMPLES[tool_name]
        source_path = adapter_temp_dir / rel_path
        assert source_path.exists(), f"Sample file for {tool_name} should exist"

        adapter_cls = ADAPTER_CLASSES[tool_name]
        adapter = adapter_cls()
        assert adapter.can_import(str(source_path)), f"{tool_name} adapter should detect its file"

        agent_json = adapter.import_from(str(source_path))

        # Verify Agent JSON v2 structure
        assert agent_json.get("schema_version") == "2.0", f"{tool_name}: expected schema_version 2.0"
        assert "identity" in agent_json, f"{tool_name}: missing identity"
        assert agent_json["identity"].get("name"), f"{tool_name}: missing identity.name"
        assert "instructions" in agent_json, f"{tool_name}: missing instructions"
        assert agent_json["instructions"].get("source") == "inline", f"{tool_name}: expected inline instructions"
        assert agent_json["instructions"].get("content"), f"{tool_name}: instructions content should not be empty"

    @pytest.mark.parametrize("tool_name", list(ADAPTER_SAMPLES.keys()))
    def test_imported_agent_has_compatibility(self, adapter_temp_dir, tool_name):
        """Imported agent should have compatibility metadata for the source tool."""
        rel_path, _ = ADAPTER_SAMPLES[tool_name]
        source_path = adapter_temp_dir / rel_path
        adapter_cls = ADAPTER_CLASSES[tool_name]
        adapter = adapter_cls()
        agent_json = adapter.import_from(str(source_path))

        compat = agent_json.get("compatibility", {})
        source = compat.get("source", "")
        assert source in tool_name or tool_name.startswith(source) or compat.get(source) is True, (
            f"{tool_name}: compatibility metadata missing or incorrect, got {compat}"
        )

    @pytest.mark.parametrize("tool_name", list(ADAPTER_SAMPLES.keys()))
    def test_imported_agent_tags(self, adapter_temp_dir, tool_name):
        """Imported agent should contain source-specific tags."""
        rel_path, _ = ADAPTER_SAMPLES[tool_name]
        source_path = adapter_temp_dir / rel_path
        adapter_cls = ADAPTER_CLASSES[tool_name]
        adapter = adapter_cls()
        agent_json = adapter.import_from(str(source_path))

        tags = agent_json.get("identity", {}).get("tags", [])
        assert "imported" in tags, f"{tool_name}: expected 'imported' tag"

    def test_all_adapters_registered(self):
        """Verify that all expected adapters are available in AdapterRegistry."""
        registry = AdapterRegistry()
        registry.register(CursorAdapter())
        registry.register(ClaudeAdapter())
        registry.register(CodeBuddyAdapter())
        registry.register(GitHubAdapter())
        registry.register(VSCodeAdapter())
        registry.register(JetBrainsAdapter())
        registry.register(OpenAIGPTsAdapter())

        infos = registry.list_adapters()
        names = [info.get("name") for info in infos]
        expected = ["cursor", "claude_code", "codebuddy", "github_copilot", "vscode_agent_mode", "jetbrains_ai_assistant", "openai_gpts"]
        for name in expected:
            assert name in names, f"Adapter '{name}' not registered, got {names}"

    @pytest.mark.parametrize("tool_name", list(ADAPTER_SAMPLES.keys()))
    def test_imported_agent_loadable_by_runtime(self, adapter_temp_dir, tool_name):
        """After import, the resulting agent.json should be loadable by AgentRuntime."""
        rel_path, _ = ADAPTER_SAMPLES[tool_name]
        source_path = adapter_temp_dir / rel_path
        adapter_cls = ADAPTER_CLASSES[tool_name]
        adapter = adapter_cls()
        agent_json = adapter.import_from(str(source_path))

        # Verify AgentRuntime can load it (has required fields)
        assert agent_json.get("identity", {}).get("name"), "AgentRuntime requires identity.name"
        instructions = agent_json.get("instructions")
        assert instructions is not None, "AgentRuntime requires instructions"
        if isinstance(instructions, dict):
            assert instructions.get("content") or instructions.get("file"), "Instructions must have content or file"
        else:
            assert isinstance(instructions, str) and instructions, "Instructions must be a non-empty string"

    def test_auto_detect_adapter(self, adapter_temp_dir):
        """AdapterRegistry should auto-detect the correct adapter."""
        registry = AdapterRegistry()
        for cls in ADAPTER_CLASSES.values():
            registry.register(cls())

        rel_path, _ = ADAPTER_SAMPLES["cursor"]
        source_path = adapter_temp_dir / rel_path

        adapter = registry.find_adapter(str(source_path))
        assert adapter is not None, "Auto-detect should find an adapter"
        info = adapter.get_info()
        assert info.get("name") == "cursor", "Auto-detect should identify cursor"

    def test_adapter_registry_create_default(self):
        """create_default_registry should have all 8 adapters."""
        from agent_compose.adapters import create_default_registry
        registry = create_default_registry()
        infos = registry.list_adapters()
        names = [info.get("name") for info in infos]
        assert len(names) >= 8, f"Expected at least 8 adapters, got {len(names)}: {names}"
